#!/usr/bin/env python3
"""Render docs/COMMANDS.md (the command reference) and docs/AGENTS.example.md
(a sample generated AGENTS.md) from the tool itself, so the committed docs
never drift from the code. Run after changing any command or its help."""

from __future__ import annotations

import io
import os
import re
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
os.environ["NO_COLOR"] = "1"
os.environ["TERM"] = "dumb"
os.environ["COLUMNS"] = "88"

from rungs import __version__  # noqa: E402
from rungs.cli import Context, build_parser, main  # noqa: E402

ANSI = re.compile(r"\x1b\[[0-9;]*m")


def strip(text: str) -> str:
    return ANSI.sub("", text)


def render_commands() -> str:
    ctx = Context(stdout=io.StringIO(), stderr=io.StringIO())
    parser = build_parser(ctx)
    out = [f"# rungs {__version__}: command reference", "",
           "_Generated by `scripts/render-docs.py` from the tool's own `--help`. Do not edit by hand._", "",
           "```", strip(parser.format_help()).rstrip(), "```", ""]
    for name, sub in ctx.subparsers.items():
        # argparse registers aliases as separate choices; keep the primary name only.
        if sub.prog.split()[-1] != name:
            continue
        out += [f"## `rungs {name}`", "", "```", strip(sub.format_help()).rstrip(), "```", ""]
    return "\n".join(out)


def render_agents_example() -> str:
    with tempfile.TemporaryDirectory() as tmp:
        project = Path(tmp) / "project"
        project.mkdir()
        out, err = io.StringIO(), io.StringIO()
        ctx = Context(cwd=project, stdout=out, stderr=err)
        code = main([
            "init", "--project", "example",
            "--agent", "claude.fable.001:xhigh:director:high",
            "--agent", "openai.astra.001:high",
            "--agent", "claude.opus.001:medium",
            "--agent", "claude.opus.reviewer:high:reviewer",
            "--agent", "claude.sonnet.001:low",
            "--agent", "claude.haiku.001:very-low",
        ], ctx=ctx)
        if code != 0:
            raise SystemExit(f"init failed ({code}): {err.getvalue()}")
        text = (project / ".rungs" / "AGENTS.md").read_text(encoding="utf-8")
    note = ("_This is the `.rungs/AGENTS.md` that `rungs init` generated for an example "
            "project with six agents. Every project gets its own, matching its roster "
            "and the installed version._\n\n")
    return strip(note + text)


def main_script() -> None:
    (ROOT / "docs" / "COMMANDS.md").write_text(render_commands(), encoding="utf-8")
    (ROOT / "docs" / "AGENTS.example.md").write_text(render_agents_example(), encoding="utf-8")
    print("wrote docs/COMMANDS.md and docs/AGENTS.example.md")


if __name__ == "__main__":
    main_script()
